amazonProperties:
  endpointUrl: https://s3.us-east-2.amazonaws.com
  accessKey: <accesskey>
  secretKey: <secret>
  bucketName: sustech/Documents
  docloc: https://<bucket>/Documents

spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 5MB
      max-request-size: 5MB
server:
  port: 8080
